# kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30000
      hostPort: 9092
      protocol: TCP
    - containerPort: 30001
      hostPort: 9644
      protocol: TCP
  - role: worker
  - role: worker