# redpanda-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
  namespace: redpanda
data:
  redpanda.yaml: |
    redpanda:
      data_directory: /var/lib/redpanda/data
      seed_servers:
        - host:
            address: redpanda-0.redpanda.redpanda.svc.cluster.local
            port: 33145
        - host:
            address: redpanda-1.redpanda.redpanda.svc.cluster.local
            port: 33145
        - host:
            address: redpanda-2.redpanda.redpanda.svc.cluster.local
            port: 33145
      rpc_server:
        address: 0.0.0.0
        port: 33145
      kafka_api:
        - address: 0.0.0.0
          port: 9092
          name: internal
      admin:
        - address: 0.0.0.0
          port: 9644
      advertised_kafka_api:
        - address: redpanda-0.redpanda.redpanda.svc.cluster.local
          port: 9092
          name: internal
      developer_mode: true